---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controllerManager:
  extraArgs:
    cluster-signing-cert-file: /etc/kubernetes/pki/ca.crt
    cluster-signing-key-file: /etc/kubernetes/pki/ca.key
kubernetesVersion: v1.17.4
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
apiServer:
  certSANs:
  - 105.1.1.1
  extraArgs:
    authorization-mode: Node,RBAC
    service-account-issuer: kubernetes.default.svc
    service-account-signing-key-file: /etc/kubernetes/pki/sa.key
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.7.105
  bindPort: 6443
---
